%sql
-- ==========================================================
-- Business Question 15
-- Build a complete RFM (Recency, Frequency, Monetary)
-- customer segmentation model
-- ==========================================================

-- ==========================================================
-- Create View
-- ==========================================================
CREATE OR REPLACE VIEW gold.vw_customer_rfm_segmentation AS

-- CTE: Calculate customer RFM metrics
WITH customer_rfm AS (

    SELECT

        c.CustomerKey,
        c.CustomerName,

        -- ==================================================
        -- Recency:
        -- Days since customer's last purchase
        -- ==================================================
        DATEDIFF(
            CURRENT_DATE(),
            MAX(d.OrderDate)
        ) AS Recency,


        -- ==================================================
        -- Frequency:
        -- Number of orders made by each customer
        -- ==================================================
        COUNT(
            DISTINCT f.SalesOrderID
        ) AS Frequency,


        -- ==================================================
        -- Monetary:
        -- Total revenue generated by customer
        -- ==================================================
        SUM(
            f.LineTotal
        ) AS Monetary


    FROM gold.fact_sales f


    -- Join customer dimension
    JOIN gold.dim_customer c
        ON f.CustomerKey = c.CustomerKey


    -- Join date dimension
    JOIN gold.dim_date d
        ON f.DateKey = d.DateKey


    GROUP BY

        c.CustomerKey,
        c.CustomerName

),


-- CTE: Create RFM scores using NTILE()
rfm_scores AS (

    SELECT

        CustomerKey,
        CustomerName,

        Recency,
        Frequency,
        Monetary,


        -- ==================================================
        -- Recency Score:
        -- Lower days since purchase = better score
        -- ==================================================
        NTILE(5) OVER(
            ORDER BY Recency DESC
        ) AS RecencyScore,


        -- ==================================================
        -- Frequency Score:
        -- More purchases = better score
        -- ==================================================
        NTILE(5) OVER(
            ORDER BY Frequency ASC
        ) AS FrequencyScore,


        -- ==================================================
        -- Monetary Score:
        -- Higher revenue = better score
        -- ==================================================
        NTILE(5) OVER(
            ORDER BY Monetary ASC
        ) AS MonetaryScore


    FROM customer_rfm

),


-- CTE: Create final RFM segment classification
rfm_segments AS (

    SELECT


        CustomerKey,
        CustomerName,

        Recency,
        Frequency,
        Monetary,


        RecencyScore,
        FrequencyScore,
        MonetaryScore,


        -- ==================================================
        -- Combine scores into RFM Score
        -- ==================================================
        CONCAT(
            RecencyScore,
            FrequencyScore,
            MonetaryScore
        ) AS RFMScore,


        -- ==================================================
        -- Customer segmentation logic
        -- ==================================================
        CASE


            -- High-value loyal customers
            WHEN RecencyScore >= 4
             AND FrequencyScore >= 4
             AND MonetaryScore >= 4
            THEN 'Champions'


            -- Customers with good value but less recent activity
            WHEN MonetaryScore >= 4
             AND FrequencyScore >= 3
            THEN 'Loyal Customers'


            -- Recently acquired customers
            WHEN RecencyScore >= 4
             AND FrequencyScore <= 2
            THEN 'New Customers'


            -- Customers with decreasing engagement
            WHEN RecencyScore <= 2
             AND FrequencyScore >= 3
            THEN 'At Risk'


            -- Customers with low activity and value
            WHEN RecencyScore <= 2
             AND FrequencyScore <= 2
             AND MonetaryScore <= 2
            THEN 'Lost Customers'


            -- Remaining customers
            ELSE 'Potential Customers'


        END AS CustomerSegment


    FROM rfm_scores

)

SELECT


    CustomerKey,
    CustomerName,

    Recency,
    Frequency,
    Monetary,

    RecencyScore,
    FrequencyScore,
    MonetaryScore,

    RFMScore,

    CustomerSegment


FROM rfm_segments;

-- ==========================================================
-- Query the View
-- ==========================================================

SELECT *

FROM gold.vw_customer_rfm_segmentation

-- Show highest-value customers first
ORDER BY

    Monetary DESC,
    Frequency DESC;
